import './App.css';
import { React } from 'react';

import LineDev from './components/LineDev';
import WenDisplay from './components/WenDisplay';
import DateTimeBar from './components/DateTimeBar';
import TriWheelHsi from './components/TriWheelHsi';
import TriWheelWen from './components/TriWheelWen';

function App() {

const wilHex = [
  {
    "num": 1,
    "hex": "\u4dc0",
    "simpinyin": "乾\nqián",
    "name": "The Creative",
    "img": "The movement of heaven is full of power.\n Thus the superior one makes themself strong and untiring.",
    "thwan": "The creative works sublime success, furthering through perseverance.",
    "line1": "\u268A",
    "line1x": "\u268Ax",
    "xline1": "x\u268A",
    "line2": "\u268A",
    "line2x": "\u268Ax",
    "xline2": "x\u268A",
    "line3": "\u268A",
    "line3x": "\u268Ax",
    "xline3": "x\u268A",
    "line4": "\u268A",
    "line4x": "\u268Ax",
    "xline4": "x\u268A",
    "line5": "\u268A",
    "line5x": "\u268Ax",
    "xline5": "x\u268A",
    "line6": "\u268A",
    "line6x": "\u268Ax",
    "xline6": "x\u268A",
    "first": "First 9:\n Hidden dragon. Do not act.",
    "second": "Second 9:\n Dragon appearing in the field.\n It furthers one to see the great one.",
    "third": "Third 9:\n All day long the superior one is creatively active.\n At nightfall ones mind is still beset with cares. Danger. No blame.",
    "fourth": "Fourth 9:\n Wavering flying over the depths. No blame.",
    "fifth": "Fifth 9:\n Flying dragon in the heavens.\n It furthers one to see the great one.",
    "sixth": "Sixth 9:\n Arrogant dragon will have cause to repent.",
    "seventh": "Six 9's:\n There appears a flight of dragons without heads.\n Good fortune."
  },
  {
    "num": 2,
    "hex": "\u4dc1",
    "simpinyin": "坤\nkūn",
    "name": "The Receptive",
    "img": "The earth's condition is receptive devotion.\n Thus the superior one who has breadth of character\n carries the outer world.",
    "thwan": "The Receptive brings about sublime success,\n furthering through the perseverance of a mare.\n If the superior one undertakes something and tries to lead,\n they go astray; But if one follows, they find guidance.\n It is favorable to find friends in the west and south,\n to forego friends in the east and north.\n Quiet perseverance brings good fortune.",
    "line1": "\u268B",
    "line1x": "\u268Bx",
    "xline1": "x\u268B",
    "line2": "\u268B",
    "line2x": "\u268Bx",
    "xline2": "x\u268B",
    "line3": "\u268B",
    "line3x": "\u268Bx",
    "xline3": "x\u268B",
    "line4": "\u268B",
    "line4x": "\u268Bx",
    "xline4": "x\u268B",
    "line5": "\u268B",
    "line5x": "\u268Bx",
    "xline5": "x\u268B",
    "line6": "\u268B",    
    "first": "First 6:\n When there is boarfrost underfoot, solid ice is not far off.",
    "second": "Second 6:\n Straight, square, great.\n Without purpose, yet nothing remains unfurthered.",
    "third": "Third 6:\n Hidden lines. One is able to remain persevering.\n If by chance you are in the service of a king,\n seek not works, but bring to completion.",
    "fourth": "Fourth 6:\n A tied-up sack. No blame, no praise.",
    "fifth": "Fifth 6:\n A yellow lower garment brings supreme good fortune.",
    "sixth": "Sixth 6:\n Dragon fight in the meadow.\n Their blood is black and yellow.",
    "seventh": "Six 6's:\n Lasting perseverance furthers."
  },
  {
    "num": 3,
    "hex": "\u4dc2",
    "simpinyin": "屯\nchún",
    "name": "Difficulty at the Beginning",
    "img": "Clouds and Thunder, thus the superior one brings order out of confusion.",
    "thwan": "Difficulty at the beginning works supreme success,\n furthering through perseverance. Nothing should be undertaken.\n It furthers one to appoint helpers.",
    "line1": "\u268A",
    "line2": "\u268B",
    "line3": "\u268B",
    "line4": "\u268B",
    "line5": "\u268A",
    "line6": "\u268B",
    "first": "First 9:\n Hesitation and hindrance. It furthers one to remain persevering. It furthers one to appoint helpers.",
    "second": "Second 6:\n Difficulties pile up. Horse and wagon part.\n The suspect is not a thief; but wants to woo when the time comes.\n The maiden is chaste, she does not pledge herself.\n Ten years- then she pledges herself.",
    "third": "Third 6:\n Whoever hunts deer without the forester loses their way in the forest.",
    "fourth": "Fourth 6:\n Horse and wagon part. Strive for union. To go brings good fortune.",
    "fifth": "Fifth 9:\n Difficulties in the blessing. A little perseverance brings good fortune.\n Great perseverance brings misfortune.",
    "sixth": "Sixth 6:\n Horse and wagon part. Bloody tears flow.",
    "seventh": ""
  },
  {
    "num": 4,
    "hex": "\u4dc3",
    "simpinyin": "蒙\nméng",
    "name": "Youthful Folly",
    "img": "A spring wells up at the foot of the mountain, the image of youth:\n thus the superior one fosters their character by thoroughness in all their endeavors.",
    "thwan": "Youthful Folly has success. It is not I who seek the young fool;\n the young fool seeks me. At the first oracle I inform them.\n If one asks two or three times, it is importunity.\n If one importunes, I give no information.\n Perseverance furthers.",
    "line1": "\u268B",
    "line2": "\u268A",
    "line3": "\u268B",
    "line4": "\u268B",
    "line5": "\u268B",
    "line6": "\u268A",
    "first": "First 6:\n To make a fool develop it furthers one to apply discipline.\n The fetters should be removed.\n To go on in this way brings humiliation.",
    "second": "Second 9:\n To bear with fools in kindliness brings good fortune.\n To know how to accomodate women brings good fortune.\n The descendant is capable of taking charge of the household.",
    "third": "Third 6:\n Take not a maiden who, when she sees a man of bronze, loses possession of herself. Nothing furthers.",
    "fourth": "Fourth 6:\n Entangled folly brings humiliation.",
    "fifth": "Fifth 6:\n Childlike folly brings good fortune.",
    "sixth": "Sixth 9:\n In punishing folly it does not further one to commit transgressions.\n The only thing that furthers is to prevent transgressions.",
    "seventh": ""
  },
  {
    "num": 5,
    "hex": "\u4dc4",
    "simpinyin": "需\nxū",
    "name": "Waiting (Nourishment)",
    "img": "Clouds rise up to heaven,\n thus the superior one eats and drinks,\n is joyous and of good cheer.",
    "thwan": "Waiting. If you are sincere, you have light and success.\n Perseverance brings good fortune. It furthers one to cross the great water.",
    "line1": "\u268A",
    "line2": "\u268A",
    "line3": "\u268A",
    "line4": "\u268B",
    "line5": "\u268A",
    "line6": "\u268B",
    "first": "First 9:\n Waiting in the meadow. It furthers one to abide in what endures. No blame.",
    "second": "Second 9:\n Waiting on the sand. There is some gossip. The end brings good fortune.",
    "third": "Third 9:\n Waiting in the mud brings about the arrival of the enemy.",
    "fourth": "Fourth 6:\n Waiting in blood. Get out of the pit.",
    "fifth": "Fifth 9:\n Waiting at meat and drink. Perseverance brings good fortune.",
    "sixth": "Sixth 6:\n One falls into the pit. Three uninvited guests arrive.\n Honor them, and in the end there will be good fortune.",
    "seventh": ""
  },
  {
    "num": 6,
    "hex": "\u4dc5",
    "simpinyin": "訟\nsòng",
    "name": "Conflict",
    "img": "Heaven and water go their opposite ways,\n thus in all their transactions,\n the superior one carefully considers the beginning.",
    "thwan": "Conflict. You are sincere and are being obstructed.\n A cautious halt halfway brings good fortune.\n Going through to the end brings misfortune.\n It furthers one to see the great man.\n It does not further one to cross the great water.",
    "line1": "\u268B",
    "line2": "\u268A",
    "line3": "\u268B",
    "line4": "\u268A",
    "line5": "\u268A",
    "line6": "\u268A",
    "first": "First 6:\n If one does not perpetuate the affair, there is a little gossip.\n In the end, good fortune comes.",
    "second": "Second 9:\n One cannot engage in conflict; one returns home, gives way.\n The people of ones town, three hundred households, remain free of guilt.",
    "third": "Third 6:\n To nourish oneself on ancient virtue induces perseverance.\n Danger. In the end, good fortune comes.\n If by chance you are in the service of a king, seek not works.",
    "fourth": "Fourth 9:\n One cannot engage in conflict. One turns back and submits to fate,\n changes one's attitude, and finds peace in perseverance.\n Good fortune.",
    "fifth": "Fifth 9:\n To contend before them brings supreme good fortune.",
    "sixth": "Sixth 9:\n Even if by chance a leather belt is bestowed on one,\n by the end of the morning it will have been snatched away three times.",
    "seventh": ""
  },
  {
    "num": 7,
    "hex": "\u4dc6",
    "simpinyin": "師\nshī",
    "name": "The Army",
    "img": "In the middle of the earth is water,\n thus the superior one increases their masses\n by generosity toward the people.",
    "thwan": "The Army needs perseverance and a strong person.\n Good fortune without blame.",
    "line1": "\u268B",
    "line2": "\u268A",
    "line3": "\u268B",
    "line4": "\u268B",
    "line5": "\u268B",
    "line6": "\u268B",
    "first": "First 6:\n An army must set forth in proper order.\n If the order is not good, misfortune threatens.",
    "second": "Second 9:\n In the midst of the army.\n Good fortune. No blame.\n The king bestows a triple decoration.",
    "third": "Third 6:\n Perchance the army carries corpses in the wagon. Misfortune.",
    "fourth": "Fourth 6:\n The army retreats. No blame.",
    "fifth": "Fifth 6:\n There is game in the field. It furthers one to catch it.\n Without blame. Let the eldest lead the army.\n The younger transports corpses;\n then perseverance brings misfortune.",
    "sixth": "Sixth 6:\n The great prince issues commands,\n founds states, vests families with fiefs.\n Inferior people should not be employed.",
    "seventh": ""
  },
  {
    "num": 8,
    "hex": "\u4dc7",
    "simpinyin": "比\nbǐ",
    "name": "Holding Together (Union)",
    "img": "On the earth is water,\n thus rulers of antiquity bestowed the different states as fiefs\n and cultivated friendly relations with the feudal lords.",
    "thwan": "Holding Together brings good fortune.\n Inquire of the oracle again whether you possess sublimity,\n constancy, and perseverance; then there is no blame.\n Those who are uncertain gradually join.\n Whoever comes too late meets with misfortune.",
    "line1": "\u268B",
    "line2": "\u268B",
    "line3": "\u268B",
    "line4": "\u268B",
    "line5": "\u268A",
    "line6": "\u268B",
    "first": "First 6:\n Hold to him in truth and loyalty;\n this is without blame. Truth, like a full earthen bowl:\n thus in the end good fortune comes from without.",
    "second": "Second 6:\n Holding fast to oneself inwardly. Perseverance brings good fortune.",
    "third": "Third 6:\n You hold together with the wrong people.",
    "fourth": "Fourth 6:\n Holding to oneself outwardly also. Perseverance brings good fortune.",
    "fifth": "Fifth 9:\n Manifestations of holding together.\n In the hunt for the ruler uses beaters on three sides only\n and foregoes game that runs off in front.\n The citizens need no warning.\n Good fortune.",
    "sixth": "Sixth 6:\n One finds no head for holding together. Misfortune.",
    "seventh": ""
  },
  {
    "num": 9,
    "hex": "\u4dc8",
    "simpinyin": "小畜\nxiǎo chù",
    "name": "The Taming Power of the Small",
    "img": "The wind drives across heaven,\n thus the superior one refines the outward aspect of their nature.",
    "thwan": "The Taming Power of the Small has success.\n Dense clouds, no rain from our western region.",
    "line1": "\u268A",
    "line2": "\u268A",
    "line3": "\u268A",
    "line4": "\u268B",
    "line5": "\u268A",
    "line6": "\u268A",
    "first": "First 9:\n Return to the way.\n How could there be blame in this?\n Good fortune.",
    "second": "Second 9:\n One allows themself to be drawn into returning.\n Good fortune.",
    "third": "Third 9:\n The spokes burst out of the wagon wheels.\n Man and wife roll their eyes.",
    "fourth": "Fourth 6:\n If you are sincere,\n blood vanishes and fear gives way.\n No blame.",
    "fifth": "Fifth 9:\n If you are sincere and loyally attached,\n you are rich in your neighbor.",
    "sixth": "Sixth 9:\n The rain comes, there is rest.\n This is due to the lasting effect of character.\n Perseverance brings the woman into danger.\n The moon is nearly full.\n If the superior one persists, misfortune comes.",
    "seventh": ""
  },
  {
    "num": 10,
    "hex": "\u4dc9",
    "simpinyin": "履\nlǚ",
    "name": "Treading (Conduct)",
    "img": "Heaven above, the lake below:\n thus the superior one discriminates between the high and low,\n and thereby fortifies the thinking of the people.",
    "thwan": "Treading upon the tail of the tiger. It does not bite the man. Success.",
    "line1": "\u268A",
    "line2": "\u268A",
    "line3": "\u268B",
    "line4": "\u268A",
    "line5": "\u268A",
    "line6": "\u268A",
    "first": "First 9:\n Simple conduct. Progress without blame.",
    "second": "Second 9:\n Treading a smooth, level course.\n The perseverance of a dark man brings good fortune.",
    "third": "Third 6:\n A one-eyed person is able to see, a lame person able to tread.\n One treads on the tail of a tiger. The tiger bites them. Misfortune.\n Thus does a warrior act on behalf of their great prince.",
    "fourth": "Fourth 9:\n One treads on the tail of the tiger. Caution and circumspection lead ultimately to good fortune. ",
    "fifth": "Fifth 9:\n Resolute conduct. Perseverance with awareness of danger.",
    "sixth": "Sixth 9:\n Look to your conduct and weigh the favorable signs.\n When everything is fulfilled, supreme good fortune comes.",
    "seventh": ""
  },
  {
    "num": 11,
    "hex": "\u4dca",
    "simpinyin": "泰\ntài",
    "name": "Peace",
    "img": "Heaven and earth unite:\n Thus the ruler divides and completes the course of heaven and earth,\n they furthers and regulates the gifts of heaven and earth, and so aid the people.",
    "thwan": "Peace. The small departs, the great approaches. Good fortune. Success.",
    "line1": "\u268A",
    "line2": "\u268A",
    "line3": "\u268A",
    "line4": "\u268B",
    "line5": "\u268B",
    "line6": "\u268B",
    "first": "First 9:\n When ribbon grass is pulled up, the sod comes with it. Each according to their kind.\n Undertakings bring good fortune.",
    "second": "Second 9:\n Bearing with the uncultured in gentleness, fording the river with resolution,\n not neglecting what is distant, not regarding one's companions:\n thus one may manage to walk in the middle.",
    "third": "Third 9:\n No plain not followed by a slope. No going not followed by a return.\n One remains persevering in danger is without blame.\n Do not complain about this truth; enjoy the good fortune you still possess.",
    "fourth": "Fourth 6:\n One flutters down, not boasting of their wealth,\n together with their neighbor, guileless and sincere.",
    "fifth": "Fifth 6:\n The sovereign I gives his daughter in marriage.\n This brings blessing and supreme good fortune.",
    "sixth": "Sixth 6:\n The wall falls back into the moat. Use no army now.\n Make your commands known within your own town.\n Perseverance brings humiliation.",
    "seventh": ""
  },
  {
    "num": 12,
    "hex": "\u4dcb",
    "simpinyin": "否\npǐ",
    "name": "Standstill (Stagnation)",
    "img": "Heaven and earth do not unite:\n thus the superior one falls back on their inner worth,\n in order to escape the difficulties.\n One does not permit themself to be honored with revenue.",
    "thwan": "Standstill. Evil people do not further the perseverance of the superior one.\n The great departs; the small approaches.",
    "line1": "\u268B",
    "line2": "\u268B",
    "line3": "\u268B",
    "line4": "\u268A",
    "line5": "\u268A",
    "line6": "\u268A",
    "first": "First 6:\n When ribbon grass is pulled up, the sod comes with it.\n Each according to their kind.\n Perseverance brings good fortune and success.",
    "second": "Second 6:\n They bear and endure; this means good fortune for inferior people.\n The standstill serves to help the great one to attain success.",
    "third": "Third 6:\n They bear shame.",
    "fourth": "Fourth 9:\n One who acts at the command of the highest remains without blame.\n Those of like mind partake of the blessing.",
    "fifth": "Fifth 9:\n Standstill is giving way. Good fortune for the great one. \n'What if it should fail, what if it should fail?'\n In this way one ties it to a cluster of mulberry shoots.",
    "sixth": "Sixth 9:\n The standstill comes to an end. First standstill, then good fortune.",
    "seventh": ""
  },
  {
    "num": 13,
    "hex": "\u4dcc",
    "simpinyin": "同人\ntóng rén",
    "name": "Fellowship with Men",
    "img": "Heaven together with fire:\n thus the superior one organizes the clans\n and makes distinctions between things.",
    "thwan": "Fellowship with men in the open. Success.\n It furthers one to cross the great water.\n The perseverance of the superior one furthers. ",
    "line1": "\u268A",
    "line2": "\u268B",
    "line3": "\u268A",
    "line4": "\u268A",
    "line5": "\u268A",
    "line6": "\u268A",
    "first": "First 9:\n Fellowship with men at the gate. No blame.",
    "second": "Second 6:\n Fellowship with men in the clan. Humiliation.",
    "third": "Third 9:\n One hides weapons in the thickets;\n one climbs the high hill in front of it.\n For three years one does not rise up.",
    "fourth": "Fourth 9:\n One climbs up on their wall; one cannot attack. Good fortune.",
    "fifth": "Fifth 9:\n People bound in fellowship first weep and lament, but afterward they laugh.\n After great struggles they succeed in meeting.",
    "sixth": "Sixth 9:\n Fellowship with men in the meadow. No remorse.",
    "seventh": ""
  },
  {
    "num": 14,
    "hex": "\u4dcd",
    "simpinyin": "大有\ndà yǒu",
    "name": "Possession in Great Measure",
    "img": "Fire in heaven above:\n thus the superior one curbs evil and furthers good,\n and thereby obeys the benevolent will of heaven.",
    "thwan": "Possession in great measure. Supreme success.",
    "line1": "\u268A",
    "line2": "\u268A",
    "line3": "\u268A",
    "line4": "\u268A",
    "line5": "\u268B",
    "line6": "\u268A",
    "first": "First 9:\n No relationship with what is harmful; there is no blame in this.\n If one remains conscious of difficulty, one remains without blame.",
    "second": "Second 9:\n A big wagon for loading. One may undertake something. No blame.",
    "third": "Third 9:\n A prince offers it to the Son of Heaven. A petty man cannot do this.",
    "fourth": "Fourth 9:\n One makes a difference between oneself and their neighbor. No blame.",
    "fifth": "Fifth 6:\n One whose truth is accessible, yet dignified, has good fortune.",
    "sixth": "Sixth 9:\n One is blessed by heaven. Good fortune. Nothing that does not further.",
    "seventh": ""
  },
  {
    "num": 15,
    "hex": "\u4dce",
    "simpinyin": "謙\nqiān",
    "name": "Modesty",
    "img": "Within the earth, a mountain:\n thus the superior one reduces that which is too much,\n and augments that which is too little.\n One weighs things and makes them equal.",
    "thwan": "Modesty creates success. The superior one carries things through.",
    "line1": "\u268B",
    "line2": "\u268B",
    "line3": "\u268A",
    "line4": "\u268A",
    "line5": "\u268B",
    "line6": "\u268B",
    "first": "First 6:\n A superior one modest about their modesty may cross the great water.\n Good fortune.",
    "second": "Second 6:\n Modesty that comes to expression.\n Perseverance brings good fortune.",
    "third": "Third 9:\n A superior one of modesty and merit.\n Carries things to conclusion.\n Good fortune.",
    "fourth": "Fourth 9:\n Nothing that would not further modesty in movement.",
    "fifth": "Fifth 6:\n No boasting of wealth before one's neighbor.\n It is favorable to attack with force.",
    "sixth": "Sixth 6:\n Modesty that comes to expression.\n It is favorable to set armies marching to chastise\n one's own city and one's country.",
    "seventh": ""
  },
  {
    "num": 16,
    "hex": "\u4dcf",
    "simpinyin": "豫\nyù",
    "name": " Enthusiasm",
    "img": "Thunder comes resounding out of the earth:\n thus the ancient rulers made music in order to honor their merit,\n and offered splendor to the Supreme Deity,\n inviting their ancestors to be present. ",
    "thwan": "Enthusiasm. It furthers one to install helpers and to set armies marching.",
    "line1": "\u268B",
    "line2": "\u268B",
    "line3": "\u268B",
    "line4": "\u268A",
    "line5": "\u268B",
    "line6": "\u268B",
    "first": "First 6:\n Enthusiasm that expresses itself brings misfortune.",
    "second": "Second 6:\n Firm as a rock. Not a whole day.\n Perseverance brings good fortune.",
    "third": "Third 6:\n Enthusiasm that looks upward creates remorse.\n Hesitation brings remorse.",
    "fourth": "Fourth 9:\n The source of enthusiasm . One achieves great things. Doubt not.\n You gather friends around you as a hair clasp gathers the hair.",
    "fifth": "Fifth 6:\n Persistently ill, and still does not die.",
    "sixth": "Sixth 6:\n Deluded enthusiasm.\n But if after completion one changes,\n there is no blame.",
    "seventh": ""
  },
  {
    "num": 17,
    "hex": "\u4dd0",
    "simpinyin": "隨\nsuí",
    "name": "Following",
    "img": "Thunder in the middle of the lake,\n thus the superior one at nightfall goes indoors for rest and recuperation.",
    "thwan": "Following has supreme success. Perseverance furthers. No blame.",
    "line1": "\u268A",
    "line2": "\u268B",
    "line3": "\u268B",
    "line4": "\u268A",
    "line5": "\u268A",
    "line6": "\u268B",
    "first": "First 9:\n The standard is changing.\n Perseverance brings good fortune.\n To go out of the door in company produces deeds.",
    "second": "Second 6:\n If one clings to the little boy, one loses the strong one.",
    "third": "Third 6:\n If one clings to the strong, one loses the weak.\n Through following one finds what one seeks.\n It furthers one to remain persevering. ",
    "fourth": "Fourth 9:\n Following creates success. Perseverance brings misfortune.\n To go one's way with sincerity brings clarity.\n How could there be blame in this?",
    "fifth": "Fifth 9:\n Sincere in the good. Good fortune.",
    "sixth": "Sixth 6:\n One meets with firm allegiance and is still further bound.\n The ruler introduces them to the Western Mountain.",
    "seventh": ""
  },
  {
    "num": 18,
    "hex": "\u4dd1",
    "simpinyin": "蠱\ngǔ",
    "name": "Work on What Has Been Spoiled (Decay)",
    "img": "The wind blows low on the mountain:\n thus the superior one stirs up the people and strengthens their spirits.",
    "thwan": "Work on What Has Been Spoiled has supreme success.\n It furthers one to cross the great water.\n Before the starting point, three days.\n After the starting point, three days.",
    "line1": "\u268B",
    "line2": "\u268A",
    "line3": "\u268A",
    "line4": "\u268B",
    "line5": "\u268B",
    "line6": "\u268A",
    "first": "First 6:\n setting right what has been spoiled by the father, if there is a son, no blame rests upon the departed father. Danger. In the end good fortune.",
    "second": "Second 9:\n Setting right what has been spoiled by the mother. One must not be too persevering.",
    "third": "Third 9:\n Setting right what has been spoiled by the father. There will be a little remorse. No great blame.",
    "fourth": "Fourth 6:\n Tolerating what has been spoiled by the father. In continuing one sees humiliation.",
    "fifth": "Fifth 6:\n Setting right what has been spoiled by the father. One meets with praise.",
    "sixth": "Sixth 9:\n One does not serve the kings and princes, sets themself to higher goals.",
    "seventh": ""
  },
  {
    "num": 19,
    "hex": "\u4dd2",
    "simpinyin": "臨\nlín",
    "name": "Approach",
    "img": "The earth above the lake:\n thus the superior one is inexhaustible in their will to teach,\n and without limits in their tolerance and protection of the people.",
    "thwan": "Approach has supreme success. Perseverance furthers.\n When the eighth month comes, there will be misfortune.",
    "line1": "\u268A",
    "line2": "\u268A",
    "line3": "\u268B",
    "line4": "\u268B",
    "line5": "\u268B",
    "line6": "\u268B",
    "first": "First 9:\n Joint approach. Perseverance brings good fortune. ",
    "second": "Second 9:\n Joint approach. Good fortune. Everything furthers.",
    "third": "Third 6:\n Comfortable approach. Nothing that would further.\n If one is induced to grieve over it, one becomes free of blame.",
    "fourth": "Fourth 6:\n Complete approach. No blame.",
    "fifth": "Fifth 6:\n Wise approach. This is right for a great prince.\n Good fortune.",
    "sixth": "Sixth 6:\n Greathearted approach. Good fortune. No blame.",
    "seventh": ""
  },
  {
    "num": 20,
    "hex": "\u4dd3",
    "simpinyin": "觀\nguān",
    "name": "Contemplation (View)",
    "img": "The wind blows over the earth:\n thus the kings of old visited the regions of the world,\n contemplated the people, and gave them instructions.",
    "thwan": "Contemplation.\n The ablution has been made, but not yet the offering.\n Full of trust they look up to the deity.",
    "line1": "\u268B",
    "line2": "\u268B",
    "line3": "\u268B",
    "line4": "\u268B",
    "line5": "\u268A",
    "line6": "\u268A",
    "first": "First 6:\n Childlike contemplation.\n For an inferior, no blame.\n For a superior, humiliation.",
    "second": "Second 6:\n Contemplation through the crack of the door.\n Furthering for the perseverance of a woman.",
    "third": "Third 6:\n Contemplation of my life decides\n the choice between advance and retreat.",
    "fourth": "Fourth 6:\n Contemplation of the light of the kingdom.\n It furthers one to exert influence as the guest of a ruler.",
    "fifth": "Fifth 9:\n Contemplation of my life. No blame.",
    "sixth": "Sixth 9:\n Contemplation of the sages life.\n The superior one is without blame.",
    "seventh": ""
  },
  {
    "num": 21,
    "hex": "\u4dd4",
    "simpinyin": "噬嗑\nshì kè",
    "name": "Biting Through",
    "img": "Thunder and lightning:\n thus the rulers of antiquity made firm the laws\n through clearly defined penalties.",
    "thwan": "Biting through has success. It is favorable to let justice be administered.",
    "line1": "\u268A",
    "line2": "\u268B",
    "line3": "\u268B",
    "line4": "\u268A",
    "line5": "\u268B",
    "line6": "\u268A",
    "first": "First 9:\n Ones feet are fastened in the stocks,\n so that his toes disappear. No blame.",
    "second": "Second 6:\n Bites through tender meat, so that their nose disappears. No blame.",
    "third": "Third 6:\n Bites on old dry meat and strikes on something poisonous.\n Slight humiliation. No blame.",
    "fourth": "Fourth 9:\n Bites on dried grisly meat. Receives metal arrows.\n It furthers one to be mindful of difficulties and to be persevering. \nGood fortune.",
    "fifth": "Fifth 6:\n Bites on dried lean meat, receives yellow gold.\n Perseveringly aware of danger.",
    "sixth": "Sixth 9:\n Ones neck is fastened in the wooden cangue,\n so that their ears disappear. Misfortune.",
    "seventh": ""
  },
  {
    "num": 22,
    "hex": "\u4dd5",
    "simpinyin": "賁\nbì",
    "name": "Grace",
    "img": "Fire at the foot of the mountain: thus does the superior one proceed when clearing up current affairs. But one does not decide controversial issues in this way.",
    "thwan": "Grace has success. In small matters it is favourable to undertake something.",
    "line1": "\u268A",
    "line2": "\u268B",
    "line3": "\u268A",
    "line4": "\u268B",
    "line5": "\u268B",
    "line6": "\u268A",
    "first": "First 9:\n One lends their grace to their toes,\n leaves the carriage, and walks.",
    "second": "Second 6:\n Lends grace to the beard on their chin.",
    "third": "Third 9:\n Graceful and moist. Constant perseverance brings good fortune.",
    "fourth": "Fourth 6:\n Grace or simplicity? A white horse comes as if on wings.\n They are not a robber, they will woo at the right time.",
    "fifth": "Fifth 6:\n Grace in hills and gardens.\n The roll of silk is meager and small.\n Humiliation, but in the end good fortune.",
    "sixth": "Sixth 9:\n Simple grace. No blame.",
    "seventh": ""
  },
  {
    "num": 23,
    "hex": "\u4dd6",
    "simpinyin": "剝\nbō",
    "name": "Splitting Apart",
    "img": "The mountain rests on the earth:\n thus those above can ensure their position\n only by giving generously to those below.",
    "thwan": "Splitting apart. It does not further one to go anywhere.",
    "line1": "\u268B",
    "line2": "\u268B",
    "line3": "\u268B",
    "line4": "\u268B",
    "line5": "\u268B",
    "line6": "\u268A",
    "first": "First 6:\n The leg of the bed is split.\n Those who persevere are destroyed.\n Misfortune.",
    "second": "Second 6:\n The bed is split at the edge.\n Those who persevere are destroyed.\n Misfortune.",
    "third": "Third 6:\n One splits with them.\n No blame.",
    "fourth": "Fourth 6:\n The bed is split up to the skin.\n Misfortune.",
    "fifth": "Fifth 6:\n A shoal of fishes.\n Favor comes through the court of women.\n Everything acts to further.",
    "sixth": "Sixth 9:\n There is a large fruit still uneaten.\n The superior one receives a carriage.\n The house of the inferior one is split apart.",
    "seventh": ""
  },
  {
    "num": 24,
    "hex": "\u4dd7",
    "simpinyin": "復\nfù",
    "name": "Return (The Turning Point)",
    "img": "Thunder within the earth:\n thus rulers of old closed the passes at the time of solstice.\n Merchants and strangers did not go about,\n and the ruler did not travel through the provinces.",
    "thwan": "Return. Success. \nGoing out and coming in without error.\n Friends come without blame.\n To and fro goes the way.\n On the seventh day comes return.\n It furthers one to have somewhere to go.",
    "line1": "\u268A",
    "line2": "\u268B",
    "line3": "\u268B",
    "line4": "\u268B",
    "line5": "\u268B",
    "line6": "\u268B",
    "first": "First 9:\n Return from a short distance.\n No need for remorse.\n Good fortune.",
    "second": "Second 6:\n Quiet return. Good fortune.",
    "third": "Third 6:\n Repeated return. Danger. No blame.",
    "fourth": "Fourth 6:\n Walking in the midst of others, one returns alone.",
    "fifth": "Fifth 6:\n Noblehearted return. No remorse.",
    "sixth": "Sixth 6:\n Missing the return.\n Misfortune.\n Misfortune from within and without.\n If armies are set marching in this way,\n one will in the end suffer a great defeat,\n disastrous for the ruler of the country.\n For ten years it will not be possible to attack again.",
    "seventh": ""
  },
  {
    "num": 25,
    "hex": "\u4dd8",
    "simpinyin": "無妄\nwú wàng",
    "name": "Innocence (The Unexpected)",
    "img": "Under heaven thunder rolls:\n all things attain the natural state of innocence,\n thus the rulers of old, rich in virtue,\n and in harmony with the time,\n fostered and nourished all beings.",
    "thwan": "Innocence. Supreme success. Perseverance furthers.\n If someone is not as they should be, they have misfortune,\n and it does not further them to undertake anything.",
    "line1": "\u268A",
    "line2": "\u268B",
    "line3": "\u268B",
    "line4": "\u268A",
    "line5": "\u268A",
    "line6": "\u268A",
    "first": "First 9:\n Innocent behavior brings good fortune.",
    "second": "Second 6:\n If one has to count on the harvest while plowing,\n or on the use of the ground while clearing it,\n it furthers one to undertake something.",
    "third": "Third 6:\n Undeserved misfortune.\n The cow that was tethered by someone is the wanderer's gain,\n the citizen's loss.",
    "fourth": "Fourth 9:\n One who can be persevering remains without blame.",
    "fifth": "Fifth 9:\n Use no medicine in an illness incurred through no fault of your own.\n It will pass of itself.",
    "sixth": "Sixth 9:\n Innocent action brings misfortune.\n Nothing furthers.",
    "seventh": ""
  },
  {
    "num": 26,
    "hex": "\u4dd9",
    "simpinyin": "大畜\ndà chù",
    "name": "The Taming Power of the Great ",
    "img": "Heaven within the mountain:\n thus the superior one acquaints themself with many sayings of antiquity\n and many deeds of the past,\n in order to strengthen their character thereby.",
    "thwan": "The Taming Power of the Great, perseverance furthers.\n Not eating at home brings good fortune.\n It furthers one to cross the great water.",
    "line1": "\u268A",
    "line2": "\u268A",
    "line3": "\u268A",
    "line4": "\u268B",
    "line5": "\u268B",
    "line6": "\u268A",
    "first": "First 9:\n Danger is at hand. It furthers one to desist.",
    "second": "Second 9:\n The axletrees are taken from the wagon.",
    "third": "Third 9:\n A good horse that follows others.\n Awareness of danger, with perseverance, furthers.\n Practice chariot driving and armed defences daily.\n It furthers one to have somewhere to go.",
    "fourth": "Fourth 6:\n The headboard of a young bull.",
    "fifth": "Fifth 6:\n The tusk of a gelded boar. Good fortune.",
    "sixth": "Sixth 9:\n One attains the way of heaven. Success.",
    "seventh": ""
  },
  {
    "num": 27,
    "hex": "\u4dda",
    "simpinyin": "頤\nyí",
    "name": "Corners of the Mouth\n (Providing Nourishment)",
    "img": "At the foot of the mountain, thunder:\n thus the superior one is careful of their words\n and temperate in eating and drinking.",
    "line1": "\u268A",
    "line2": "\u268B",
    "line3": "\u268B",
    "line4": "\u268B",
    "line5": "\u268B",
    "line6": "\u268A",
    "thwan": "The corners of the mouth.\n Perseverance brings good fortune.\n Pay heed to the providing of nourishment\n and to what one seeks\n to fill their own mouth with.",
    "first": "First 9:\n You let your magic tortoise go, and look at me\n with the corners of your mouth drooping.\n Misfortune.",
    "second": "Second 6:\n Turning to the summit for nourishment,\n deviating from the path to seek nourishment from the hill.\n Continuing to do this brings misfortune.",
    "third": "Third 6:\n Turning away from nourishment.\n Perseverance brings misfortune.\n Do not act thus for ten years.\n Nothing serves to further.",
    "fourth": "Fourth 6:\n Turning to the summit for provision of nourishment\n brings good fortune.\n Spying about with sharp eyes like a tiger\n with insatiable craving. No blame.",
    "fifth": "Fifth 6:\n Turning from the path.\n To remain persevering brings good fortune.\n One should not cross the great water.",
    "sixth": "Sixth 9:\n The source of nourishment.\n Awareness of danger brings good fortune.\n It furthers one to cross the great water.",
    "seventh": ""
  },
  {
    "num": 28,
    "hex": "\u4ddb",
    "simpinyin": "大過\ndà guò",
    "name": "Preponderance of the Great",
    "img": "The lake rises above the trees:\n thus the superior one, when they stand alone, is unconcerned.\n And if they have to renounce the world,\n they are undaunted. ",
    "thwan": "Preponderance of the Great.\n The ridgepole sags to the breaking point.\n It furthers one to have somewhere to go. Success.",
    "line1": "\u268B",
    "line2": "\u268A",
    "line3": "\u268A",
    "line4": "\u268A",
    "line5": "\u268A",
    "line6": "\u268B",
    "first": "First 6:\n To spread white rushes underneath. No blame.",
    "second": "Second 9:\n A dry poplar sprouts at the root.\n An older man takes a young wife. Everything furthers.",
    "third": "Third 9:\n The ridgepole sags to the breaking point. Misfortune.",
    "fourth": "Fourth 9:\n The ridgepole is braced. Good fortune.\n If there are ulterior motives, it is humiliating. ",
    "fifth": "Fifth 9:\n A withered poplar puts forth flowers.\n An older woman takes a husband.\n No blame. No praise.",
    "sixth": "Sixth 6:\n One must go through the water.\n It goes over one's head.\n Misfortune. No blame.",
    "seventh": ""
  },
  {
    "num": 29,
    "hex": "\u4ddc",
    "simpinyin": "坎\nkǎn",
    "name": "The Abysmal (Water)",
    "img": "Water flows on uninterruptedly and reaches its goal:\n thus the superior one walks in lasting virtue and carries on the business of teaching. ",
    "thwan": "The Abysmal repeated.\n If you are sincere, you have success in your heart.\n And whatever you do succeeds.",
    "line1": "\u268B",
    "line2": "\u268A",
    "line3": "\u268B",
    "line4": "\u268B",
    "line5": "\u268A",
    "line6": "\u268B",
    "first": "First 6:\n Repetition of the Abymsal.\n In the abyss one falls into a pit.\n Misfortune.  ",
    "second": "Second 9:\n The abyss is dangerous. One should strive to attain small things only.",
    "third": "Third 6:\n Forward and backward, abyss on abyss.\n In danger like this, pause at first and wait,\n otherwise you will fall into a pit in the abyss.\n Do not act in this way.",
    "fourth": "Fourth 6:\n A jug of wine, a bowl of rice with it;\n Earthen vessels simply handed in through the window.\n There is certainly no blame in this.",
    "fifth": "Fifth 9:\n The abyss is not filled to overflowing,\n it is filled only to the rim. No blame.",
    "sixth": "Sixth 6:\n Bound with cords and ropes, shut in between thorn-hedged prison walls:\n for three years one does not find the way.\n\n Misfortune.",
    "seventh": ""
  },
  {
    "num": 30,
    "hex": "\u4ddd",
    "simpinyin": "離\nlí",
    "name": "The Clinging (Fire)",
    "img": "That which is bright rises twice:\n thus the great one, by perpetuating this brightness,\n illumines the four quarters of the world.",
    "thwan": "The Clinging. Perseverance furthers.\n It brings success. Care of the cow brings good fortune.",
    "line1": "\u268A",
    "line2": "\u268B",
    "line3": "\u268A",
    "line4": "\u268A",
    "line5": "\u268B",
    "line6": "\u268A",
    "first": "First 9:\n The footprints run crisscross. If one is seriously intent, no blame.",
    "second": "Second 6:\n Yellow light. Supreme good fortune.",
    "third": "Third 9:\n In the light of the setting sun,\n people either beat the pot and sing\n or loudly bewail the approach of old age.\n Misfortune.",
    "fourth": "Fourth 9:\n Its coming is sudden; it flames up,\n dies down, is thrown away.",
    "fifth": "Fifth 6:\n Tears in floods, sighing and lamenting.\n Good fortune.",
    "sixth": "Sixth 9:\n The ruler uses one to march forth and chastise.\n Then it is best to kill the leaders and take captive the followers.\n No blame.",
    "seventh": ""
  },
  {
    "num": 31,
    "hex": "\u4dde",
    "simpinyin": "咸\nxián",
    "name": "Influence (Wooing)",
    "img": "A lake on the mountain:\n thus the superior one encourages people to approach\n by their readiness to receive them.",
    "thwan": "Influence. Success. Perseverance furthers.\n To take a maiden to wife brings good fortune.",
    "line1": "\u268B",
    "line2": "\u268B",
    "line3": "\u268A",
    "line4": "\u268A",
    "line5": "\u268A",
    "line6": "\u268B",
    "first": "First 6:\n The influence shows itself in the big toe.",
    "second": "Second 6:\n The influence shows itself in the calves of the legs.\n Misfortune. Delay brings good fortune.",
    "third": "Third 9:\n The influence shows itself in the thighs.\n Holds to that which follows it.\n To continue is humiliating.",
    "fourth": "Fourth 9:\n Perseverance brings good fortune. Remorse disappears.\n If one is agitated in mind, and their thoughts go here and there,\n only those friends on whom they fix their conscious thoughts will follow.",
    "fifth": "Fifth 9:\n The influence shows itself in the back of the neck. No remorse.",
    "sixth": "Sixth 6:\n The influence shows itself in the jaws, cheeks and tongue.",
    "seventh": ""
  },
  {
    "num": 32,
    "hex": "\u4ddf",
    "simpinyin": "恆\nhéng",
    "name": "Duration",
    "img": "Thunder and wind:\n thus the superior one stands firm\n and does not change their direction.",
    "thwan": "Duration. Success. No blame.\n Perseverance furthers.\n It furthers one to have somewhere to go.",
    "line1": "\u268B",
    "line2": "\u268A",
    "line3": "\u268A",
    "line4": "\u268A",
    "line5": "\u268B",
    "line6": "\u268B",
    "first": "First 6:\n Seeking duration too hastily brings misfortune persistently.\n Nothing that would further.",
    "second": "Second 9:\n Remorse disappears.",
    "third": "Third 9:\n One who dares not give duration\n to their character meets with disgrace.\n Persistent humiliation.",
    "fourth": "Fourth 9:\n No game in the field.",
    "fifth": "Fifth 6:\n Giving duration to one's character through perseverance.\n This is good fortune for the feminine,\n misfortune for the masculine.",
    "sixth": "Sixth 6:\n Restlessness as an enduring condition brings misfortune.",
    "seventh": ""
  },
  {
    "num": 33,
    "hex": "\u4de0",
    "simpinyin": "遯\ndùn",
    "name": "Retreat",
    "img": "Mountain under heaven:\n thus the superior one keeps the inferior one at a distance,\n not angrily but with reserve.",
    "thwan": "Retreat. Success. In what is small, perseverance furthers.",
    "line1": "\u268B",
    "line2": "\u268B",
    "line3": "\u268A",
    "line4": "\u268A",
    "line5": "\u268A",
    "line6": "\u268A",
    "first": "First 6:\n At the tail in retreat.\n This is dangerous.\n One must not wish to undertake anything.",
    "second": "Second 6:\n One holds the other fast with yellow oxhide.\n No one can tear them loose.",
    "third": "Third 9:\n A halted retreat is nerve-wracking and dangerous.\n To retain people as commonfolk and midservants brings good fortune.",
    "fourth": "Fourth 9:\n Voluntary retreat brings good fortune to the superior one and downfall to the inferior.",
    "fifth": "Fifth 9:\n Friendly retreat. Perseverance brings good fortune.",
    "sixth": "Sixth 9:\n Cheerful retreat. Everything serves to further.",
    "seventh": ""
  },
  {
    "num": 34,
    "hex": "\u4de1",
    "simpinyin": "大壯\ndà zhuàng",
    "name": "The Power of the Great",
    "img": "Thunder in heaven above:\n thus the superior one does not tread upon paths\n that do not accord with established order.",
    "thwan": "The Power of the Great. Perseverance furthers.",
    "line1": "\u268A",
    "line2": "\u268A",
    "line3": "\u268A",
    "line4": "\u268A",
    "line5": "\u268B",
    "line6": "\u268B",
    "first": "First 9:\n Power in the toes.\n Continuing brings misfortune.\n This is certainly true.",
    "second": "Second 9:\n Perseverance brings good fortune.",
    "third": "Third 9:\n The inferior one works through power.\n The superior one does not act thus.\n To continue is dangerous.\n A goat butts against a hedge and gets its horns tangled.",
    "fourth": "Fourth 9:\n Perseverance brings good fortune.\n Remorse disappears.\n The hedge opens; there is no entanglement.\n Power depends upon the axle of a big cart.",
    "fifth": "Fifth 6:\n Loses the goat with ease. No remorse.",
    "sixth": "Sixth 6:\n A goat butts against a hedge.\n It cannot go backward, it cannot go forward.\n Nothing serves to further.\n If one notes the difficulty,\n this brings good fortune.",
    "seventh": ""
  },
  {
    "num": 35,
    "hex": "\u4de2",
    "simpinyin": "晉\njìn",
    "name": "Progress",
    "img": "The sun rises over the earth:\n thus the superior one themself brightens their bright virtue.",
    "thwan": "Progress. The powerful prince is honored with horses in large numbers.\n In a single day one is granted audience three times.",
    "line1": "\u268B",
    "line2": "\u268B",
    "line3": "\u268B",
    "line4": "\u268A",
    "line5": "\u268B",
    "line6": "\u268A",
    "first": "First 6:\n Progressing, but turned back.\n Perseverance brings good fortune.\n If one meets no confidence, one should remain calm.\n No mistake.",
    "second": "Second 6:\n Progressing, but in sorrow.\n Perseverance brings good fortune.\n Then one obtains great happiness from one's ancestress.",
    "third": "Third 6:\n All are in accord. Remorse disappears.",
    "fourth": "Fourth 9:\n Progress like a hamster.\n Perseverance brings danger.",
    "fifth": "Fifth 6:\n Remorse disappears.\n Take not gain and loss to heart.\n Undertakings bring good fortune.\n Everything serves to further.",
    "sixth": "Sixth 9:\n Making progress with the horns is permissible\n only for the purpose of punishing ones own city.\n To be conscious of the danger brings good fortune.\n No blame.\n Perseverance brings humiliation.",
    "seventh": ""
  },
  {
    "num": 36,
    "hex": "\u4de3",
    "simpinyin": "明夷\nmíng yí",
    "name": "Darkening of the Light",
    "img": "The light has sunken into the earth:\n thus does the superior one live with the great mass:\n though one veils their light, it still shines.",
    "thwan": "Darkening of the Light.\n In adversity it furthers one to be persevering.",
    "line1": "\u268A",
    "line2": "\u268B",
    "line3": "\u268A",
    "line4": "\u268B",
    "line5": "\u268B",
    "line6": "\u268A",
    "first": "First 9:\n Darkening of the light during flight.\n One lowers their wings.\n The superior one does not eat for three days on their wanderings.\n But one has somewhere to go.\n The host has occasion to gossip about them.",
    "second": "Second 6:\n Darkening of the light injures one in the left thigh.\n One gives aid with the strength of a horse.\n Good fortune.",
    "third": "Third 9:\n Darkening of the light during the hunt in the south.\n Their great leader is captured.\n One must not expect perseverance too soon.",
    "fourth": "Fourth 6:\n One penetrates the left side of the belly.\n One gets at the very heart of the darkening of the light,\n and leaves the gate and courtyard.",
    "fifth": "Fifth 6:\n Darkening of the light as with Prince Chi.\n Perseverance furthers.",
    "sixth": "Sixth 9:\n Not light but darkness.\n First one climbed up to heaven,\n then they plunged into the depths of the earth.",
    "seventh": ""
  },
  {
    "num": 37,
    "hex": "\u4de4",
    "simpinyin": "家人\njiā rén",
    "name": "The Family (The Clan)",
    "img": "Wind comes forth from fire:\n thus the superior one has substance in their words\n and duration in their way of life.",
    "thwan": "The Family.\n The perseverance of the woman furthers.",
    "line1": "\u268A",
    "line2": "\u268B",
    "line3": "\u268A",
    "line4": "\u268B",
    "line5": "\u268A",
    "line6": "\u268A",
    "first": "First 9:\n Firm seclusion within the family.\n Remorse disappears.",
    "second": "Second 6:\n She should not follow her whims.\n She must attend within to the food.\n Perseverance brings good fortune.",
    "third": "Third 9:\n When tempers flare up in the family,\n too great severity brings remorse.\n Good fortune nonetheless.\n When woman and child dally and laugh,\n it leads in the end to humiliation.",
    "fourth": "Fourth 6:\n She is the treasure of the house.\n Great good fortune.",
    "fifth": "Fifth 9:\n As a ruler one approaches their family.\n Fear not.\n Good fortune.",
    "sixth": "Sixth 9:\n Ones work commands respect.\n In the end good fortune comes.",
    "seventh": ""
  },
  {
    "num": 38,
    "hex": "\u4de5",
    "simpinyin": "睽\nkuí",
    "name": "Opposition",
    "img": "Fire above, lake below:\n thus amid fellowship the superior one retains their individuality.",
    "thwan": "Opposition. In small matters, good fortune.",
    "line1": "\u268A",
    "line2": "\u268A",
    "line3": "\u268B",
    "line4": "\u268A",
    "line5": "\u268B",
    "line6": "\u268A",
    "first": "First 9:\n Remorse disappears.\n If you lose your horse, do not run after it;\n it will come back of its own accord.\n When you see evil people, guard yourself against mistakes.",
    "second": "Second 9:\n One meets their lord in a narrow street. No blame.",
    "third": "Third 6:\n One sees the wagon dragged back, the oxen halted,\n one's hair and nose cutoff.\n Not a good beginning, but a good end.",
    "fourth": "Fourth 9:\n Isolated in opposition, one meets a like-minded individual\n with whom one can associate in good faith.\n Despite the danger, no blame.",
    "fifth": "Fifth 6:\n Remorse disappears.\n The companion bites their way through the wrappings.\n If one meets their companion, how could it be a mistake?",
    "sixth": "Sixth 9:\n Isolated in opposition, one sees one's companion\n as a pig covered with dirt,\n as a wagon full of devils.\n First one draws a bow against them,\n then one lays the bow aside.\n They are not a robber;\n they will woo at the right time.\n As one leaves, rain falls;\n then good fortune comes.",
    "seventh": ""
  },
  {
    "num": 39,
    "hex": "\u4de6",
    "simpinyin": "蹇\njiǎn",
    "name": "Obstruction",
    "img": "Water on the mountain:\n thus the superior one turns their attention to themself\n and molds their character.",
    "thwan": "Obstruction. The southwest furthers.\n The northeast does not further.\n It furthers one to see the great one.\n Perseverance brings good fortune.",
    "line1": "\u268B",
    "line2": "\u268B",
    "line3": "\u268A",
    "line4": "\u268A",
    "line5": "\u268A",
    "line6": "\u268B",
    "first": "First 6:\n Going leads to obstruction,\n coming meets with praise.",
    "second": "Second 6:\n The king's servant is beset by obstruction upon obstruction,\n but it is their own fault.",
    "third": "Third 9:\n Going leads to obstruction;\n Hence one comes back.",
    "fourth": "Fourth 6:\n Going leads to obstructions,\n coming leads to union.",
    "fifth": "Fifth 9:\n In the midst of the greatest obstructions,\n friends come.",
    "sixth": "Sixth 6:\n Going leads to obstructions,\n coming leads to great good fortune.",
    "seventh": ""
  },
  {
    "num": 40,
    "hex": "\u4de7",
    "simpinyin": "解\nxiè",
    "name": "Deliverance",
    "img": "Thunder and rain set in:\n thus the superior one pardons mistakes and forgives misdeeds.",
    "thwan": "Deliverance.\n The southwest furthers.\n If there is no longer anything where one has to go,\n return brings good fortune.\n If there is still something where one has to go,\n hastening brings good fortune.",
    "line1": "\u268B",
    "line2": "\u268A",
    "line3": "\u268B",
    "line4": "\u268A",
    "line5": "\u268B",
    "line6": "\u268B",
    "first": "First 6:\n Without blame.",
    "second": "Second 9:\n One kills three foxes in the field\n and receives a yellow arrow.\n Perseverance brings good fortune.",
    "third": "Third 6:\n If one carries a burden on their back\n and nonetheless rides in a carriage,\n one thereby encourages robbers to draw near.\n Perseverance leads to humiliation.",
    "fourth": "Fourth 9:\n Deliver yourself from your great toe.\n Then the trustworthy companion arrives.",
    "fifth": "Fifth 6:\n If only the superior one can deliver themself,\n it brings good fortune.\n Thus one proves to the inferior\n that the superior is in earnest.",
    "sixth": "Sixth 6:\n The prince shoots at a hawk on a high wall and kills it.\n Everything serves to further.",
    "seventh": ""
  },
  {
    "num": 41,
    "hex": "\u4de8",
    "simpinyin": "損\nsǔn",
    "name": "Decrease",
    "img": "At the foot of the mountain, the lake:\n thus the superior one controls their anger and restrains their instincts.",
    "thwan": "Decrease combined with sincerity brings supreme good fortune without blame.\n One may be persevering in this.\n It furthers one to undertake something.\n How is this to be carried out?\n One may use two small bowls for the sacrifice.",
    "line1": "\u268A",
    "line2": "\u268A",
    "line3": "\u268B",
    "line4": "\u268B",
    "line5": "\u268B",
    "line6": "\u268A",
    "first": "First 9:\n Going quickly when one's tasks are finished is without blame.\n But one must reflect on how much one may decrease others.",
    "second": "Second 9:\n Perseverance furthers. To undertake something brings misfortune.\n Without decreasing oneself,\n one is able to bring increase to others.",
    "third": "Third 6:\n When three people journey together, their number decreases by one.\n When one journeys alone, they find a companion.",
    "fourth": "Fourth 6:\n If one decreases their faults,\n it makes the other hasten to come and rejoice.\n No blame.",
    "fifth": "Fifth 6:\n Someone does indeed increase him.\n Ten pairs of tortoises cannot oppose it. Supreme good fortune.",
    "sixth": "Sixth 9:\n If one is increased without depriving others, there is no blame.\n Perseverance brings good fortune.\n It furthers one to undertake something.\n One obtains servants but no longer has a separate home.",
    "seventh": ""
  },
  {
    "num": 42,
    "hex": "\u4de9",
    "simpinyin": "益\nyì",
    "name": "Increase",
    "img": "Wind and thunder:\n thus if the superior one sees good, they imitate it;\n if one has faults, one rids themselves of them. ",
    "thwan": "Increase. It furthers one to undertake something.\n It furthers one to cross the great water.",
    "line1": "\u268A",
    "line2": "\u268B",
    "line3": "\u268B",
    "line4": "\u268B",
    "line5": "\u268A",
    "line6": "\u268A",
    "first": "First 9:\n It furthers one to accomplish great deeds.\n Supreme good fortune. No blame.",
    "second": "Second 6:\n Someone does indeed increase increase the subject;\n ten pairs of tortoises cannot oppose it.\n Constant perseverance brings good fortune.\n The  ruler presents the subject before God.\n Good fortune.",
    "third": "Third 6:\n One is enriched through unfortunate events.\n No blame, if you are sincere and walk in the middle,\n and report with a seal to the prince.",
    "fourth": "Fourth 6:\n If you walk in the middle and report to the prince,\n the prince will follow.\n It furthers one to be used in the removal of the capitol.",
    "fifth": "Fifth 9:\n If in truth you have a kind heart, ask not.\n Supreme good fortune.\n Truly, kindness will be recognized as your virtue.",
    "sixth": "Sixth 9:\n The subject brings increase to no one.\n Indeed, someone even strikes the subject.\n One does not keep their heart constantly steady.\n Misfortune.",
    "seventh": ""
  },
  {
    "num": 43,
    "hex": "\u4dea",
    "simpinyin": "夬\nguài",
    "name": "Break-Through (Revolution)",
    "img": "The lake has risen up to heaven:\n thus the superior one dispenses riches downward\n and refrains from resting on their virtue.",
    "thwan": "Break-Through.\n One must resolutely make the matter\n known at the court of the king.\n It must be announced truthfully. Danger.\n It is necessary to notify one's own city.\n It does not further to resort to arms.\n It furthers one to undertake something.",
    "line1": "\u268A",
    "line2": "\u268A",
    "line3": "\u268A",
    "line4": "\u268A",
    "line5": "\u268A",
    "line6": "\u268B",
    "first": "First 9:\n Mighty in the forward-striding toes.\n When one goes and is not equal to the task,\n one makes a mistake.",
    "second": "Second 9:\n A cry of alarm.\n Arms at evening and at night.\n Fear nothing.",
    "third": "Third 9:\n To be powerful in the cheekbones brings misfortune.\n The superior one is firmly resolved.\n One walks alone and is caught in the rain.\n One is bespattered,\n and people murmer against them. No blame.",
    "fourth": "Fourth 9:\n There is no skin on ones thighs, and walking comes hard.\n If one were to let themself be led like a sheep, remorse would disappear.\n But if these words are heard they will not be believed.",
    "fifth": "Fifth 9:\n In dealing with weeds,\n firm resolution is necessary.\n Walking in the middle remains free of blame.",
    "sixth": "Sixth 6:\n No cry. In the end misfortune comes.",
    "seventh": ""
  },
  {
    "num": 44,
    "hex": "\u4deb",
    "simpinyin": "姤\ngòu",
    "name": "Coming to Meet",
    "img": "Under heaven, wind:\n thus does the prince act when disseminating their commands\n and proclaiming them to the four quarters of heaven.",
    "thwan": "Coming to meet. The maiden is powerful.\n One should not marry such a maiden.",
    "line1": "\u268B",
    "line2": "\u268A",
    "line3": "\u268A",
    "line4": "\u268A",
    "line5": "\u268A",
    "line6": "\u268A",
    "first": "First 6:\n It must be checked with a brake of bronze.\n Perseverance brings good fortune.\n If one lets it take its course, one experiences misfortune.\n Even a lean pig has it in them to rage around.",
    "second": "Second 9:\n There is a fish in the tank.\n No blame. Does not further guests.",
    "third": "Third 9:\n There is no skin on ones thighs, and walking comes hard.\n If one is mindful of the danger, no great mistake is made.",
    "fourth": "Fourth 9:\n No fish in the tank. This leads to misfortune.",
    "fifth": "Fifth 9:\n A melon covered with willow leaves.\n Hidden lines. Then it drops down to one from heaven.",
    "sixth": "Sixth 9:\n One comes to meet with their own horns.\n Humiliation. No blame.",
    "seventh": ""
  },
  {
    "num": 45,
    "hex": "\u4dec",
    "simpinyin": "萃\n cuì",
    "name": "Gathering Together\n (Massing)",
    "img": "Over the earth, the lake:\n thus the superior one renews their weapons in order to meet the unforeseen.",
    "thwan": "Gathering together. Success.\n The ruler approaches their ancestral temple.\n It furthers one to see the great one.\n This brings success. Perseverance furthers.\n To bring great offerings creates good fortune.\n It furthers one to undertake something.",
    "line1": "\u268B",
    "line2": "\u268B",
    "line3": "\u268B",
    "line4": "\u268B",
    "line5": "\u268A",
    "line6": "\u268B",
    "first": "First  6:\n If you are sincere, but not to the end,\n there will sometimes be confusion, sometimes gathering together.\n If you call out, then after one grasp of the hand you can laugh again.\n Regret not. Going is without blame.",
    "second": "Second 6:\n Letting oneself be drawn brings good fortune and remains blameless.\n If one is sincere, it furthers one to bring even a small offering.",
    "third": "Third 6:\n Gathering together amid sighs.\n Nothing that would further. Going is without blame.",
    "fourth": "Fourth 9: Great good fortune. No blame.",
    "fifth": "Fifth 9:\n If in gathering together one has position,\n this brings no blame.\n If there are some who are not yet sincerely in the work, sublime and enduring perseverance is needed.\n Then remorse disappears.",
    "sixth": "Sixth 6:\n Lamenting and sighing, floods of tears. No blame.",
    "seventh": ""
  },
  {
    "num": 46,
    "hex": "\u4ded",
    "simpinyin": "升\nshēng",
    "name": "Pushing Upward",
    "img": "Within the earth, wood grows:\n thus the superior one of devoted character heaps up small things\n in order to achieve something high and great.",
    "thwan": "Pushing upward has supreme success.\n One must see the great one.\n Fear not.\n Departure towards the south brings good fortune.",
    "line1": "\u268B",
    "line2": "\u268A",
    "line3": "\u268A",
    "line4": "\u268B",
    "line5": "\u268B",
    "line6": "\u268B",
    "first": "First 6:\n Pushing upward that meets with confidence brings great good fortune.",
    "second": "Second 9:\n If one is sincere,\n it furthers one to bring even a small offering.\n No blame.",
    "third": "Third 9:\n One pushes upward into an empty city.",
    "fourth": "Fourth 6:\n The ruler offers the subject Mount Ch'i.\n Good fortune. No blame.",
    "fifth": "Fifth 6:\n Perseverance brings good fortune.\n One pushes upward by steps.",
    "sixth": "Sixth 6:\n Pushing upward in darkness.\n It furthers one to be unremittingly persevering.",
    "seventh": ""
  },
  {
    "num": 47,
    "hex": "\u4dee",
    "simpinyin": "困\nkùn",
    "name": "Oppression\n (Exhaustion)",
    "img": "There is no water in the lake:\n thus the superior one stakes their life on following their will.",
    "thwan": "Oppression. Success. Perseverance.\n The great one brings about good fortune.\n No blame.\n When one has something to say, it is not believed.",
    "line1": "\u268B",
    "line2": "\u268A",
    "line3": "\u268B",
    "line4": "\u268A",
    "line5": "\u268A",
    "line6": "\u268B",
    "first": "First 6:\n One sits oppressed under a bare tree and strays into a gloomy valley.\n For three years one sees nothing.",
    "second": "Second 9:\n One is oppressed while at meat and drink.\n The one with the scarlet knee bands is just coming.\n It furthers one to offer sacrifice. To set forth brings misfortune.\n No blame.",
    "third": "Third 6:\n One permits themself to be oppressed by stone,\n and leans on thorns and thistles.\n One enters their house and does not see their wife.\n Misfortune.",
    "fourth": "Fourth 9:\n One approaches very quietly,\n oppressed in a golden carriage.\n Humiliation, but the end is reached.",
    "fifth": "Fifth 9:\n Ones nose and feet are cut off.\n Oppression at the hands of the one with the purple knee bands.\n Joy comes softly.\n It furthers one to make offerings and libations.",
    "sixth": "Sixth 6:\n One is oppressed by creeping vines.\n One moves uncertainly and says, \"Movement brings remorse.\" If one feels remorse over this and makes a start, good fortune comes.",
    "seventh": ""
  },
  {
    "num": 48,
    "hex": "\u4def",
    "simpinyin": "井\njǐng",
    "name": "The Well",
    "img": "Water over wood:\n thus the superior one encourages the people at their work,\n and exhorts them to help one another.",
    "thwan": "The Well. The town may be changed,\n but the well cannot be changed.\n It neither decreases nor increases.\n They come and go and draw from the well.\n If one gets down almost to the water\n and the rope does not reach the water\n or the jug breaks, it brings misfortune.",
    "line1": "\u268B",
    "line2": "\u268A",
    "line3": "\u268A",
    "line4": "\u268B",
    "line5": "\u268A",
    "line6": "\u268B",
    "first": "First 6:\n One does not drink the mud of the well.\n No animals come to an old well.",
    "second": "Second 9:\n At the wellhole one shoots fish.\n The jug is broken and leaks.",
    "third": "Third 9:\n The well is cleaned, but no one drinks from it.\n This is my heart's sorrow, for one might draw from it.\n If the ruler were clear-minded, good fortune might be enjoyed in common.",
    "fourth": "Fourth 6:\n The well is being lined. No blame.",
    "fifth": "Fifth 9:\n In the well there is a clear,\n cold spring from which one can drink.",
    "sixth": "Sixth 6:\n One draws from the well without hindrance.\n It is dependable. Supreme good fortune.",
    "seventh": ""
  },
  {
    "num": 49,
    "hex": "\u4df0",
    "simpinyin": "革\ngé",
    "name": "Revolution\n (Molting)",
    "img": "Fire in the lake:\n thus the superior one sets the calendar\n in order and makes the seasons clear.",
    "thwan": "Revolution. On your own day you are believed.\n Supreme success, furthering through perseverance.\n Remorse disappears.",
    "line1": "\u268A",
    "line2": "\u268B",
    "line3": "\u268A",
    "line4": "\u268A",
    "line5": "\u268A",
    "line6": "\u268B",
    "first": "First 9:\n Wrapped in the hide of a yellow cow.",
    "second": "Second 6:\n When one's own day comes, one may create revolution.\n Starting brings good fortune. No blame.",
    "third": "Third 9:\n Starting brings misfortune.\n Perseverance brings brings danger.\n When talk of revolution has gone the rounds three times,\n one may commit themself,\n and others will believe them.",
    "fourth": "Fourth 9:\n Remorse disappears. The people believe the subject.\n Changing the form of government brings good fortune.",
    "fifth": "Fifth 9:\n The great one changes like a tiger.\n Even before one questions the oracle they are believed.",
    "sixth": "Sixth 6:\n The superior one changes like a panther.\n The inferior one molts in the face.\n Starting brings misfortune.\n To remain persevering brings good fortune.",
    "seventh": ""
  },
  {
    "num": 50,
    "hex": "\u4df1",
    "simpinyin": "鼎\ndǐng",
    "name": "The Caldron",
    "img": "Fire over wood:\n thus the superior one consolidates their fate\n by making their position correct.",
    "thwan": "The Caldron. Supreme good fortune. Success.",
    "line1": "\u268B",
    "line2": "\u268A",
    "line3": "\u268A",
    "line4": "\u268A",
    "line5": "\u268B",
    "line6": "\u268A",
    "first": "First 6:\n A ting with legs upturned.\n Furthers removal of stagnating substance.\n One takes a concubine for the sake of her son.\n No blame.",
    "second": "Second 9:\n There is food in the ting.\n My comrades are envious, but they cannot harm me.\n Good fortune.",
    "third": "Third 9:\n The handle of the ting is altered.\n One is impeded in their way of life.\n The fat of the pheasant is not eaten.\n Once rain falls, remorse is spent.\n Good fortune comes in the end.",
    "fourth": "Fourth 9:\n The legs of the ting are broken.\n The prince's meal is spilled\n and their person is soiled.\n Misfortune.",
    "fifth": "Fifth 6:\n The ting has yellow handles,\n golden carrying rings.\n Perseverance furthers.",
    "sixth": "Sixth 9:\n The ting has rings of jade.\n Great good fortune.\n Nothing that would not act to further.",
    "seventh": ""
  },
  {
    "num": 51,
    "hex": "\u4df2",
    "simpinyin": "震\nzhèn",
    "name": "The Arousing\n (Shock, Thunder)",
    "img": "Thunder repeated:\n thus in fear and trembling the superior one\n sets their life in order and examines themself.",
    "thwan": "Shock brings success.\n Shock comes- uh oh!\n Laughing words- ha ha!\n The shock terrifies for a hundred miles,\n and one does not let fall the sacrificial spoon and chalice.",
    "line1": "\u268A",
    "line2": "\u268B",
    "line3": "\u268B",
    "line4": "\u268A",
    "line5": "\u268B",
    "line6": "\u268B",
    "first": "First 9:\n Shock comes bringing danger.\n A hundred thousand times you lose your treasures\n and must climb the nine hills.",
    "second": "Second 6:\n Shock comes bringing danger.\n A hundred thousand times you lose your treasures\n and must climb the nine hills.\n Do not go in pursuit of them.\n After seven days you will get them back again.",
    "third": "Third 6:\n Shock comes and makes one distraught.\n If shock spurs to action one remains free of misfortune.",
    "fourth": "Fourth 9:\n Shock is mired.",
    "fifth": "Fifth 6:\n Shock goes here and there.\n Danger. However, nothing at all is lost.\n Yet there are things to be done.",
    "sixth": "Sixth 6:\n Shock brings ruin and terrified gazing around.\n Going ahead brings misfortune.\n If it has not yet touched one's own body,\n but has reached one's neighbor first,\n there is no blame.\n One's comrades have something to talk about.",
    "seventh": ""
  },
  {
    "num": 52,
    "hex": "\u4df3",
    "simpinyin": "艮\n gèn",
    "name": "Keeping Still\n (Mountain)",
    "img": "Mountains standing close together:\n thus the superior one does not permit\n their thoughts to go beyond their situation.",
    "thwan": "Keeping still. Keeping ones back still\n so that one no longer feels their body.\n One goes into their courtyard\n and does not see their people.\n No blame.",
    "line1": "\u268B",
    "line2": "\u268B",
    "line3": "\u268A",
    "line4": "\u268B",
    "line5": "\u268B",
    "line6": "\u268A",
    "first": "First 6:\n Keeping ones toes still. No blame. Continued perseverance furthers.",
    "second": "Second 6:\n Keeping ones calves still. One cannot rescue who they follow. Their heart is not glad.",
    "third": "Third 9:\n Keeping ones hips still. Making ones sacrum stiff. Dangerous. The heart suffocates.",
    "fourth": "Fourth 6:\n Keeping ones trunk still. No blame.",
    "fifth": "Fifth 6:\n Keeping ones jaw still. The words have order. Remorse disappears.",
    "sixth": "Sixth 9:\n Noblehearted keeping still. Good fortune.",
    "seventh": ""
  },
  {
    "num": 53,
    "hex": "\u4df4",
    "simpinyin": "漸\njiàn",
    "name": "Development\n (Gradual Progress)",
    "img": "On the mountain, a tree:\n thus the superior one abides in dignity and virtue,\n in order to improve the mores.",
    "thwan": "Development. The maiden is given in marriage.\n Good fortune. Perseverance furthers.",
    "line1": "\u268B",
    "line2": "\u268B",
    "line3": "\u268A",
    "line4": "\u268B",
    "line5": "\u268A",
    "line6": "\u268A",
    "first": "First 6:\n The wild goose gradually draws near the shore.\n The young son is in danger.\n There is talk. No blame.",
    "second": "Second 6:\n The wild goose gradually draws near the cliff.\n Eating and drinking in peace and concord.\n Good fortune.",
    "third": "Third 9:\n The wild goose gradually draws from near the plateau.\n One goes forth and does not return.\n The woman carries a child but does not bring it forth.\n Misfortune. It furthers one to fight off robbers.",
    "fourth": "Fourth 6:\n The wild goose gradually draws near the tree.\n Perhaps it will find a flat branch.\n No blame.",
    "fifth": "Fifth 9:\n The wild goose gradually draws near the summit.\n For three years the woman has no child.\n In the end nothing can hinder her.\n Good fortune.",
    "sixth": "Sixth 9:\n The wild goose gradually draws near the cloud heights.\n Its feathers can be used for the sacred dance.\n Good fortune.",
    "seventh": ""
  },
  {
    "num": 54,
    "hex": "\u4df5",
    "simpinyin": "歸妹\nguī mèi",
    "name": "The Marrying Maiden",
    "img": "Thunder over the lake:\n thus the superior one understands the transitory\n in the light of the eternity of the end.",
    "thwan": "The Marrying Maiden. Undertakings bring misfortune.\n Nothing that would further.",
    "line1": "\u268A",
    "line2": "\u268A",
    "line3": "\u268B",
    "line4": "\u268A",
    "line5": "\u268B",
    "line6": "\u268B",
    "first": "First 9:\n The marrying maiden as a concubine.\n A crippled person who is able to walk.\n Undertakings bring good fortune.",
    "second": "Second 9:\n A one-eyed person who is able to see.\n The perseverance of a solitary person furthers",
    "third": "Third 6:\n The marrying maiden as a slave.\n One marries a concubine.",
    "fourth": "Fourth 9:\n The marrying maiden draws out the allotted time.\n A late marriage comes in due course. ",
    "fifth": "Fifth 6:\n The sovereign I gave his daughter in marriage.\n The embroidered garments of the princess\n were not as gorgeous as those of the servingmaid.\n The moon that is nearly full brings good fortune.",
    "sixth": "Sixth 6:\n The woman holds the basket, but there are no fruits in it.\n One stabs the sheep but no blood flows.\n Nothing that acts to further.",
    "seventh": ""
  },
  {
    "num": 55,
    "hex": "\u4df6",
    "simpinyin": "豐\nfēng",
    "name": "Abundance\n (Fullness)",
    "img": "Both thunder and lightning come:\n thus the superior one decides lawsuits and carries out punishments.",
    "thwan": "Abundance has success. The ruler attains abundance.\n Be not sad. Be like the sun at midday.",
    "line1": "\u268A",
    "line2": "\u268B",
    "line3": "\u268A",
    "line4": "\u268A",
    "line5": "\u268B",
    "line6": "\u268B",
    "first": "First 9:\n When one meets their destined ruler,\n they can be together ten days,\n and it is not a mistake.\n Going meets with recognition.",
    "second": "Second 6:\n The curtain is of such fullness that the polestars can be seen at noon.\n Through going one meets with mistrust and hate.\n If one rouses them through truth,\n good fortune comes.",
    "third": "Third 9:\n The underbrush is of such abundance\n that the small stars can be seen at noon.\n One breaks their right arm.\n No blame.",
    "fourth": "Fourth 9:\n The curtain is of such fullness\n that the polestars can be seen at noon.\n One meets with their ruler,\n who is of like kind.\n Good fortune.",
    "fifth": "Fifth 6:\n Lines are coming,\n blessing and fame draw near.\n Good fortune.",
    "sixth": "Sixth 6:\n Ones house is in a state of abundance.\n One screens off their family.\n One peers through the gate and no longer perceives anyone.\n For three years one sees nothing.\n Misfortune.",
    "seventh": ""
  },
  {
    "num": 56,
    "hex": "\u4df7",
    "simpinyin": "旅\nlǚ",
    "name": "The Wanderer",
    "img": "Fire on the mountain:\n thus the superior one is clear-minded\n and cautious in imposing penalties,\n and protracts no lawsuits.",
    "thwan": "The Wanderer. Success through smallness.\n Perseverance brings good fortune to the wanderer.",
    "line1": "\u268B",
    "line2": "\u268B",
    "line3": "\u268A",
    "line4": "\u268A",
    "line5": "\u268B",
    "line6": "\u268A",
    "first": "First 6:\n If the wanderer busies themself with trivial things,\n one draws down misfortune on themself.",
    "second": "Second 6:\n The wanderer comes to an inn.\n One has their property with them.\n One wins the steadfastness of a young servant.",
    "third": "Third 9:\n The wanderer's inn burns down.\n One loses the steadfastness of their young servant.",
    "fourth": "Fourth 9:\n The wanderer rests in a shelter.\n One obtains their property and an ax.\n My heart is not glad.",
    "fifth": "Fifth 6:\n One shoots a pheasant.\n It drops with the first arrow.\n In the end this brings both praise and office.",
    "sixth": "Sixth 9:\n The bird's nest burns up.\n The wanderer laughs at first,\n then must lament and weep.\n Through carelessness one loses their cow.",
    "seventh": ""
  },
  {
    "num": 57,
    "hex": "\u4df8",
    "simpinyin": "巽\n xùn",
    "name": "The Gentle\n (The Penetrating, Wind)",
    "img": "Winds following one upon the other:\n thus the superior one spreads their commands abroad\n and carries out their undertakings.",
    "thwan": "The Gentle. Success through what is small.\n It furthers one to have somewhere to go.\n It furthers one to see the great man.",
    "line1": "\u268B",
    "line2": "\u268A",
    "line3": "\u268A",
    "line4": "\u268B",
    "line5": "\u268A",
    "line6": "\u268A",
    "first": "First 6:\n In advancing and retreating,\n the perseverance of a warrior furthers.",
    "second": "Second 9:\n Penetration under the bed.\n Priests and magicians are used in great number.\n Good fortune. No blame.",
    "third": "Third 9:\n Repeated penetration. Humiliation.",
    "fourth": "Fourth 6:\n Remorse vanishes.\n During the hunt three kinds of game are caught.",
    "fifth": "Fifth 9:\n Perseverance brings good fortune.\n Remorse vanishes.\n Nothing that does not further.\n No beginning, but an end.\n Before the change, three days.\n After the change, three days.\n Good fortune.",
    "sixth": "Sixth 9:\n Penetration under the bed.\n One loses property and their ax.\n Perseverance brings misfortune.",
    "seventh": ""
  },
  {
    "num": 58,
    "hex": "\u4df9",
    "simpinyin": "兌\nduì",
    "name": "The Joyous\n (Lake)",
    "img": "Lakes resting one on the other:\n thus the superior one joins with their friends for discussion and practice.",
    "thwan": "The Joyous. Success. Perseverance is favorable.",
    "line1": "\u268A",
    "line2": "\u268A",
    "line3": "\u268B",
    "line4": "\u268A",
    "line5": "\u268A",
    "line6": "\u268B",
    "first": "First 9:\n Contended joyousness. Good fortune.",
    "second": "Second 9:\n Sincere joyousness. Good fortune. Remorse disappears.",
    "third": "Third 6:\n Coming joyousness. Misfortune. ",
    "fourth": "Fourth 9:\n Joyousness that is weighed is not at peace.\n After ridding themself of mistakes one has joy.",
    "fifth": "Fifth 9:\n Sincerity toward disintegrating influences is dangerous.",
    "sixth": "Sixth 6:\n Seductive joyousness.",
    "seventh": ""
  },
  {
    "num": 59,
    "hex": "\u4dfa",
    "simpinyin": "渙\nhuàn",
    "name": "Dispersion\n (Dissolution)",
    "img": "The wind drives over the water:\n thus the rulers of old sacrificed to the Lord and built temples.",
    "thwan": "Dispersion. Success.\n The ruler approaches their temple.\n It furthers one to cross the great water.\n Perseverance furthers.",
    "line1": "\u268B",
    "line2": "\u268A",
    "line3": "\u268B",
    "line4": "\u268B",
    "line5": "\u268A",
    "line6": "\u268A",
    "first": "First 6:\n One brings help with the strength of a horse.\n Good fortune.",
    "second": "Second 9:\n At the dissolution one hurries to that which supports them.\n Remorse disappears.",
    "third": "Third 6:\n One dissolves themself. No remorse.",
    "fourth": "Fourth 6:\n One dissolves their bond with their group.\n Supreme good fortune. Dispersion leads in turn to accumulation.\n This is something that ordinary people would not think of.",
    "fifth": "Fifth 9:\n Ones loud cries are as dissolving as sweat.\n Dissolution! A ruler abides without blame.",
    "sixth": "Sixth 9:\n One dissolves their blood.\n Departing, keeping at a distance,\n going out, is without blame.",
    "seventh": ""
  },
  {
    "num": 60,
    "hex": "\u4dfb",
    "simpinyin": "節\njié",
    "name": "Limitation",
    "img": "Water over lake:\n thus the superior one creates number and measure,\n and examines the nature of virtue and correct conduct.",
    "thwan": "Limitation. Success.\n Galling limitation must not be persevered in.",
    "line1": "\u268A",
    "line2": "\u268A",
    "line3": "\u268B",
    "line4": "\u268B",
    "line5": "\u268A",
    "line6": "\u268B",
    "first": "First 9:\n Not going out of the door and the courtyard is without blame.",
    "second": "Second 9:\n Not going out of the gate and the courtyard brings misfortune.",
    "third": "Third 6:\n One who knows no limitation will have cause to lament. No blame.",
    "fourth": "Fourth 6:\n Contended limitation. Success.",
    "fifth": "Fifth 9:\n Sweet limitation brings good fortune.\n Going brings esteem.",
    "sixth": "Sixth 6:\n Galling limitation.\n Perseverance brings misfortune.\n\n Remorse disappears.",
    "seventh": ""
  },
  {
    "num": 61,
    "hex": "\u4dfc",
    "simpinyin": "中孚\nzhōng fú",
    "name": "Inner Truth",
    "img": "Wind over lake:\n thus the superior one discusses criminal cases\n in order to delay executions.",
    "thwan": "Inner truth. Pigs and fishes.\n Good fortune.\n It furthers one to cross the great water.\n Perseverance fuirthers.",
    "line1": "\u268A",
    "line2": "\u268A",
    "line3": "\u268B",
    "line4": "\u268B",
    "line5": "\u268A",
    "line6": "\u268A",
    "first": "First 9:\n Being prepared brings good fortune. If there are secret designs, it is disquieting.",
    "second": "Second 9:\n A crane calling in the shade. Its young answers it. \"I have a goblet of good spirits and I will share it with you.\"",
    "third": "Third 6:\n One finds a comrade. Now one beats the drum, now one stops. Now one sobs, now one sings.",
    "fourth": "Fourth 6:\n The moon nearly at the full. The team horse goes astray. No blame.",
    "fifth": "Fifth 9:\n One possesses truth, which links together. No blame.",
    "sixth": "Sixth 9:\n Cockcrow penetrating to heaven. Perseverance brings misfortune.",
    "seventh": ""
  },
  {
    "num": 62,
    "hex": "\u4dfd",
    "simpinyin": "小過\n xiǎo guò",
    "name": "Preponderance of the Small",
    "img": "Thunder on the mountain:\n thus in ones conduct\n the superior gives preponderance to reverence.\n In bereavement one gives preponderance to grief.\n In their expenditures one gives preponderance to thrift. ",
    "thwan": "Preponderance of the small. Success.\n Perseverance furthers.\n Small things may be done;\n great things should not be done.\n The flying bird brings the message:\n it is not well to strive upward,\n it is well to remain below.\n Great good fortune.",
    "line1": "\u268B",
    "line2": "\u268B",
    "line3": "\u268A",
    "line4": "\u268A",
    "line5": "\u268B",
    "line6": "\u268B",
    "first": "First 6:\n The bird meets with misfortune through flying.",
    "second": "Second 6:\n She passes by her ancestor and meets her ancestress.\n One does not meet thier prince and meets the official.\n No blame.",
    "third": "Third 9:\n If one is not extremely careful,\n somebody may come up from behind and strike.\n Misfortune.",
    "fourth": "Fourth 9:\n No blame. One meets them without passing by.\n Going brings danger. One must be on guard.\n Do not act. Be constantly persevering.",
    "fifth": "Fifth 6:\n Dense clouds, no rain from our western territory.\n The prince shoots and hits who is in the cave.",
    "sixth": "Sixth 6:\n One is passed by, without meeting.\n The flying bird leaves. Misfortune.\n This means bad luck and injury.",
    "seventh": ""
  },
  {
    "num": 63,
    "hex": "\u4dfe",
    "simpinyin": "既濟\njì jì",
    "name": "After Completion",
    "img": "Water over fire:\n thus the superior one takes thought of misfortune\n and arms themself against it in advance.",
    "thwan": "After completion.\n Success in small matters.\n Perseverance furthers.\n At the beginning good fortune,\n at the end disorder.",
    "line1": "\u268A",
    "line2": "\u268B",
    "line3": "\u268A",
    "line4": "\u268B",
    "line5": "\u268A",
    "line6": "\u268B",
    "first": "First 9:\n One brakes their wheels.\n The fox gets its tail in the water.\n No blame.",
    "second": "Second 6:\n The woman loses the curtain of her carriage.\n Do not run after it;\n on the seventh day you will get it.",
    "third": "Third 9:\n The illustrious ancestor disciplines the Devil Country.\n After three years one conquers it.\n Inferior people must not be employed.",
    "fourth": "Fourth 6:\n The finest clothes turn to rags.\n Be careful all day long.",
    "fifth": "Fifth 9:\n The neighbor in the east who slaughters an ox\n does not attain as much real happiness\n as the neighbor in the west\n with their small offering.",
    "sixth": "Sixth 6:\n The fox gets its head in the water. Danger.",
    "seventh": ""
  },
  {
    "num": 64,
    "hex": "\u4dff",
    "simpinyin": "未濟\n wèi jì \n ",
    "name": "Before Completion",
    "img": "Fire over water:\n thus the superior one is careful\n in the differentiation of things,\n so that each finds its place.",
    "thwan": "Before completion. Success.\n But if the little fox,\n after nearly completing the crossing,\n gets its tail in the water,\n there is nothing that would further.",
    "line1": "\u268B",
    "line2": "\u268A",
    "line3": "\u268B",
    "line4": "\u268A",
    "line5": "\u268B",
    "line6": "\u268A",
    "first": "First 6:\n The fox gets its tail in the water.\n Humiliating.",
    "second": "Second 9:\n One brakes their wheels.\n Perseverance brings good fortune. ",
    "third": "Third 6:\n Before completion, attack brings misfortune.\n It furthers one to cross the great water.",
    "fourth": "Fourth 9:\n Perseverance brings good fortune.\n Remorse disappears.\n Shock, thus to discipline the Devil's Country.\n For three years, great realms are awarded.",
    "fifth": "Fifth 6:\n Perseverance brings good fortune. No remorse.\n The light of the superior one is true. Good fortune.",
    "sixth": "Sixth 9:\n There is drinking of wine in genuine confidence.\n No blame. But if one wets their head, one loses it, in truth.",
    "seventh": ""
  }
];

const tri = [
  {
    "num": 1,
    "glyph": "\u2630",
    "name": "chien",
    "meaning": "heaven creation father",
    "dirhsi": "S",
    "dirwen": "NW"
  },
  {
    "num": 2,
    "glyph": "\u2631",
    "name": "tui",
    "meaning": "lake joy",
    "dirhsi": "SE",
    "dirwen": "W"
  },
  {
    "num": 3,
    "glyph": "\u2632",
    "name": "li",
    "meaning": "fire clinging",
    "dirhsi": "E",
    "dirwen": "S"
  },
  {
    "num": 4,
    "glyph": "\u2633",
    "name": "chen",
    "meaning": "thunder shock",
    "dirhsi": "NE",
    "dirwen": "E"
  },
  {
    "num": 5,
    "glyph": "\u2634",
    "name": "sun",
    "meaning": "wind penetrating",
    "dirhsi": "SW",
    "dirwen": "SE"
  },
  {
    "num": 6,
    "glyph": "\u2635",
    "name": "kan",
    "meaning": "water pitfall danger",
    "dirhsi": "W",
    "dirwen": "N"
  },
  {
    "num": 7,
    "glyph": "\u2636",
    "name": "ken",
    "meaning": "mountain stillness",
    "dirhsi": "NW",
    "dirwen": "NE"
  },
  {
    "num": 8,
    "glyph": "\u2637",
    "name": "kun",
    "meaning": "earth receptive mother",
    "dirhsi": "N",
    "dirwen": "SW"
  }
]


return (
<div className="App">
<DateTimeBar
  wilHex={wilHex} />
<WenDisplay
  wilHex={wilHex} />
<LineDev />
<TriWheelHsi 
  tri={tri}/>
<TriWheelWen
  tri={tri} />
</div>
);
}
 
export default App;

// Calendar:

// Take destructured date object and write function to translate input into lunar and goddess calendar equivalents. Define structure for calendar.

// 

// 

//DateTimeBar:


// Write a form to input a specific gregorian date / time that is default to the current date / time.

// Replace the number specifying the changing line with logic to change the position of x to align with the changing line.

// write handler to increment timeCode up / down. Render updated date / time for blossoms shown.




//Tri:


//toggle trigram info

//Create and style Hsi and Wen Element wheels 